---
- name: Install and start Apache HTTP Server
  hosts: all
  become: yes
  tasks:
    - name: Install Apache on Debian-based systems
      apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Apache on Red Hat-based systems
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Ensure Apache is running on Debian-based systems
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure Apache is running on Red Hat-based systems
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Check Apache status on Debian-based systems
      command: systemctl status apache2
      register: result
      ignore_errors: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Check Apache status on Red Hat-based systems
      command: systemctl status httpd
      register: result
      ignore_errors: yes
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Print Apache status
      debug:
        var: result.stdout_lines
