---
- name: Install and start Apache HTTP Server
  hosts: all
  become: yes
  tasks:
    - name: Install Apache on Debian-based systems
      apt:
        name: apache2
        state: present
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Install Apache on Red Hat-based systems
      yum:
        name: httpd
        state: present
      when: ansible_distribution in ['RedHat', 'CentOS', 'Fedora']

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution in ['RedHat', 'CentOS', 'Fedora']



